### ISSUE TITLE
When using as a container rather than a modal, z-index should not be 1,000,000

### ISSUE THREAD

**Issue by jlek** [auth0/lock#2059]
### Describe the problem

Hello,

We are using Lock on Classic Universal Login, setting the [`container`](https://auth0.com/docs/libraries/lock/lock-configuration#container-string-) property to the ID of empty div, so that lock renders in that div, instead of as a pop-up modal. 

We added a "support" pop-up widget on the page, but the Lock widgets overlays the support widget, because it has a really high z-index. Please see the attached screenshot: 

![image](https://user-images.githubusercontent.com/22636008/138859517-b4e741d5-0d06-4d44-90fe-40708a1b4388.png)

### What was the expected behaviour?

If the `container` option is set, `z-index` should not be set. 

### Reproduction

1. Put an empty div with an ID in an HTML file
2. Add a script tag that runs lock, setting the `container` property to the ID of the div
3. Add some sort of modal pop-up to the page that has a z-index of less that 1,000,000, confirm that it renders behind the Lock widget

### Environment

- **Version of this library used:** 11.27
- **Which framework are you using, if applicable:** Not applicable
- **Other modules/plugins/libraries that might be involved:** Not applicable
- **Any other relevant information you think would be useful:** Not applicable

**Comment by stevehobbsdev** [comment]
Thanks for your patience with this @jlek, it's been a busy quarter.

Are you just able to override the z-index style to remove it in your case, or provide a more appropriate value? Something like:

```css
.auth0-lock.auth0-lock {
  z-index: 100;
}
```

My only concern with doing something depending if `container` is set that it might inadvertently break people who rely n this behaviour. We could add an option to control it but we don't want to add more complexity to configuration if we dont' have to. This feels like it could be handle with custom/overridden styles.

**Comment by jlek** [comment]
Yes, we managed to get it to work like this:

```CSS
/*
  * Targets the main Lock widget.
  * Even though we are rendering the Lock widget in a div, rather than as a pop-up modal (by setting the container property),
  * The widget still gets really high z-index of 1,000,000.
  * This means that when the Zendesk support widget opens on a small display,
  * the Lock widget actually overlaps the support widget, even though the latter is a modal and should always be on top.
  *
  * We raised a Github Issue about this with Auth0: https://github.com/auth0/lock/issues/2059
  * so in a future version we can fix the following:
  *
  * TODO Remove this CSS in the future if the above issue gets resolved
  */
.auth0-lock.auth0-lock {
  z-index: initial !important;
}
```

Works fine, but it's a shame we had to use `!important`. It's not very intuitive either - maybe the documentation for the container property can be updated to let users know about this?
