### ISSUE TITLE
No way to scroll down if window size is smaller that whole content

### ISSUE THREAD

**Issue by pose** [auth0/lock#215]
![scroll-issue](https://cloud.githubusercontent.com/assets/419703/9721391/161d88f6-5570-11e5-8a9e-c7bfcee3ee3a.gif)

**Comment by cwilgenhoff** [comment]
Below I propose a potential fix to this problem but stills need more tuning.

1 - Wrap **a0-oneste** step div with an outer div.
2 - Apply the following styles to it:

```css
{
    position: relative;
    top: 0;
    bottom: 0;
    width: 100%;
    height: 100%;
    overflow-y: auto;
}
```
3 - When clicked into Login button hide body's overflow.
4 - Enjoy.

![image](https://cloud.githubusercontent.com/assets/1410978/10026256/073e4b4a-6137-11e5-866f-855585c4071a.png)

**Issues with this approach**

The vertical centering of the modal window is lost after applying. An option to overcome this is to avoid using table-cell displays and instead use flexbox for aligning the boxes, the down side is that the impact can be quite big.

What do you think?
