### ISSUE TITLE
Problems with CSS starting with 8.0

### ISSUE THREAD

**Issue by neverfox** [auth0/lock#277]
I'm submitting this both to reopen #276, and add that the style for the submit button has an inline color specification that cannot be overridden as in 7.x (there may be more things like this but I haven't studied it fully). The reason that I'm reopening the issue from #276 is that it wasn't a problem in 7.x either, which suggests that something about the way 8.0 changed the injection of styles now causes the following CSS reset rule (found in normalize.css) to interfere with the way Lastpass' background image displays (the offending part being the `background-size` setting found in normalize.css):

```css
*:not(body) {
  background-repeat: no-repeat;
  background-position: 50%;
  background-size: cover;
}
```
